// src/lib/components/primitives/TextInput.svelte
<script lang="ts">
	import clsx from 'clsx';

	export let placeholder: string = 'Enter text here...';
	export let className = '';
	export let label: string = '';
	export let isTextarea: boolean = false;
	export let error: boolean = false;
	export let maxLength: number = 100;
	export let id: string = '';
	export let value: string = '';
	export let type: string = 'text';
	export let trailingAddon: string = '';

	function typeAction(node: HTMLInputElement) {
		node.type = type;
	}
</script>

<div class="w-full">
	{#if label}
		<div class="text-[12px] md:text-xs font-semibold text-light-2 mb-1.5">
			{label}
		</div>
	{/if}

	{#if isTextarea}
		<textarea
			bind:value
			class={clsx(
				'py-2.5 px-5 text-base md:text-sm rounded bg-dark-1 text-white placeholder-light-4 border border-light-4 focus:border-highlight outline-none w-full duration-75 resize-y max-h-[400px] min-h-[50px]',
				className
			)}
			on:change
			maxlength={maxLength}
			{placeholder}
			name={id}
			title={id}
			{id}
			cols={30}
			rows={10}
		/>
	{:else}
		<div
			class={clsx(
				'text-base md:text-sm rounded bg-dark-1 text-white placeholder-light-4 border border-light-4 focus-within:border-highlight outline-none w-full duration-75 flex items-center justify-start overflow-hidden',
				error && '!border-red-500'
			)}
		>
			{#if trailingAddon}
				<span class="py-2.5 pl-5 pr-0 text-light-3"> {trailingAddon} </span>
			{/if}
			<input
				bind:value
				on:change
				{id}
				aria-label={id}
				title={id || placeholder}
				maxlength={maxLength}
				class={clsx(
					'py-2.5 px-5 outline-none border-none bg-transparent w-full',
					className,
					trailingAddon && 'pl-0'
				)}
				{placeholder}
				use:typeAction
			/>
		</div>
	{/if}
</div>

// apps/web/src/components/primitives/TextInput/TextInput.tsx
import React from 'react'
import clsx from 'clsx'

type Props = {
  placeholder?: string
  className?: string
  label?: string
  isTextarea?: boolean
  maxLength?: number
  id: string
}

const TextInput = React.forwardRef(
  (
    {
      placeholder = 'Enter text here...',
      className = '',
      label = '',
      maxLength,
      id,
      isTextarea = false
    }: Props,
    ref: any
  ) => (
    <div className="w-full max-w-sm">
      {label ? (
        <div className="text-[10px] md:text-xs font-bold text-light-2 mb-1.5">
          {label}
        </div>
      ) : (
        ''
      )}

      {!isTextarea ? (
        <input
          id={id}
          aria-label={id}
          maxLength={maxLength}
          className={clsx(
            'py-2.5 px-5 text-sm md:text-[15px] rounded bg-dark-1 text-white placeholder-light-4 border border-light-4 focus:border-highlight outline-none w-full duration-75',
            className
          )}
          placeholder={placeholder}
          ref={ref}
          type="text"
        />
      ) : (
        <textarea
          className={clsx(
            'py-2.5 px-5 text-sm md:text-[15px] rounded bg-dark-1 text-white placeholder-light-4 border border-light-4 focus:border-highlight outline-none w-full duration-75 resize-y',
            className
          )}
          maxLength={maxLength}
          placeholder={placeholder}
          ref={ref}
          name={id}
          id={id}
          cols={30}
          rows={10}
        ></textarea>
      )}
    </div>
  )
)

export default TextInput
