// apps/web/src/components/common/Heading.tsx
import clsx from 'clsx'
import React from 'react'

type Props = {
  children: React.ReactNode
  className?: string
  withUnderline?: boolean
  type?: 'h1' | 'h2' | 'h3' | 'h4'
}

function Heading({
  children,
  type = 'h1',
  className,
  withUnderline = false
}: Props) {
  return (
    <div
      className={clsx(
        'text-light-1 font-bold text-2xl',
        withUnderline && 'half-underline',
        className
      )}
      dangerouslySetInnerHTML={{
        __html: `<${type} className='' >${children}</${type}>`
      }}
    ></div>
  )
}

export default Heading

// src/lib/components/common/Heading.svelte
<script lang="ts">
	import clsx from 'clsx';

	export let className: string = '';
	export let text: string = '';
	export let withUnderline: boolean = false;
	export let type: 'h1' | 'h2' | 'h3' | 'h4' = 'h1';
</script>

<div class={clsx('text-light-1 font-bold text-2xl', withUnderline && 'half-underline', className)}>
	{@html `<${type}> ${text} </${type}>`}
</div>
