// src/lib/components/primitives/Button.svelte
<script lang="ts">
	import clsx from 'clsx';

	export let label: string = '';
	export let className: string = '';
	export let primary: boolean = false;
	export let disabled: boolean = false;
</script>

<button
	aria-label={label}
	title={label}
	on:click
	class={clsx(
		'font-medium py-2 px-4 text-center text-sm bg-dark-1 text-light-1 border rounded border-light-4 duration-75 flex items-center gap-1.5 justify-center custom-border ',
		primary && 'primary bg-highlight border-highlight',
		disabled && 'opacity-50 cursor-not-allowed',
		className
	)}
	{disabled}
>
	<slot />
</button>

// apps/web/src/components/primitives/Button/Button.tsx
import React from 'react'
import clsx from 'clsx'

type Props = {
  label: string
  className?: string
  children?: React.ReactNode
  primary?: boolean
  disabled?: boolean
  onClick?: () => void
}

function Button({
  label,
  className = '',
  children = 'Button',
  onClick,
  disabled,
  primary
}: Props) {
  return (
    <button
      aria-label={label}
      onClick={onClick}
      className={clsx(
        'font-semibold py-2 px-4 text-center text-sm bg-dark-1 text-light-1 border rounded border-light-4 duration-75 flex items-center gap-1.5 justify-center',
        primary && 'primary bg-highlight border-highlight',
        disabled && 'opacity-50',
        className
      )}
      disabled={disabled}
    >
      {children}
    </button>
  )
}

export default Button
