// apps/web/src/components/primitives/Card/Card.tsx
import React from 'react'
import clsx from 'clsx'
import ParallelLines from '~/icons/ParallelLines'
import Rect1 from '~/icons/Rect1'
import Circle1 from '~/icons/Circle1'

type Props = {
  children: React.ReactNode
}

function Card({ children }: Props) {
  return (
    <div
      className={clsx(
        'bg-white bg-opacity-[1.5%] border border-white/10 rounded-[12px] py-4 px-6 relative overflow-hidden'
      )}
    >
      <ParallelLines className="absolute top-[-10px] left-[-10px] z-[-1]" />
      <Rect1 className="absolute top-[50%] right-0 z-[-1]" />
      <Circle1 className="absolute bottom-[-10px] left-[-10px] z-[-1]" />

      {children}
    </div>
  )
}

export default Card

// src/lib/components/primitives/Card.svelte
<script lang="ts">
	import clsx from 'clsx';
	import ParallelLines from '$icons/ParallelLines.svelte';
	import Rect1 from '$icons/Rect1.svelte';
	import Circle1 from '$icons/Circle1.svelte';

	export let large: boolean = false;
	export let className: string = '';
	export let noBgImages: boolean = false;
</script>

<div
	class={clsx(
		'bg-white bg-opacity-[1.5%] border border-white/10 rounded-[12px] py-4 px-6 relative overflow-hidden',
		className
	)}
>
	{#if !noBgImages}
		<ParallelLines
			className={clsx(
				' absolute z-[-1]',
				large ? 'top-[-6px] left-[10%] w-[130px] md:w-[160px]' : 'top-[-6px] left-[-6px] w-[100px]'
			)}
		/>
		<Rect1
			className={clsx(
				'absolute z-[-1]',
				large ? 'top-[50%] right-0 w-[100px] md:w-[160px]' : 'top-[45%] right-0 w-[90px]'
			)}
		/>
		<Circle1
			className={clsx(
				'absolute z-[-1]',
				large ? 'bottom-[-60px] left-[20%] w-[130px] md:w-[150px]' : 'bottom-[-50px] left-[-10px] w-[130px]'
			)}
		/>
	{/if}

	<slot />
</div>
