// apps/web/src/components/primitives/SelectDropdown/SelectDropdown.tsx
import React from 'react'

type Props = {
  options: Option[]
  id?: string
  label?: string
}

type Option = {
  id: number
  value: string
}

function SelectDropdown({
  options,
  id = `select`,
  label = 'label here:'
}: Props) {
  return (
    <div className="dropdown-menu">
      <div className="text-[10px] md:text-xs font-bold text-light-2 mb-1.5">
        {label}
      </div>

      <select
        name="select-menu"
        className="py-2.5 px-6 border border-light-3 outline-none bg-dark-1 rounded appearance-none text-sm md:text-[15px] relative focus:border-highlight !pr-14"
        id={id}
        required
      >
        {options.map((e, i) => (
          <option value={e.value} selected={i === 0} key={e.id}>
            {e.value}
          </option>
        ))}
      </select>
    </div>
  )
}

export default SelectDropdown

// src/lib/components/primitives/SelectDropdown.svelte
<script lang="ts">
	type Option = {
		id: number;
		value: string;
	};
	export let options: Option[] = [];
	export let value: string = options[0].value;
	export let id: string = 'select';
	export let label: string = 'label here:';
</script>

<div class="dropdown-menu">
	<div class="mb-1.5 text-[12px] font-semibold text-light-2">{label}</div>

	<select
		name="select-menu"
		class="relative appearance-none rounded border border-light-3 bg-dark-1 py-2.5 px-5 !pr-14 outline-none focus:border-highlight"
		{id}
		title={id}
		required
		on:change
		{value}
	>
		{#each options as option, i}
			<option value={option.value} selected={i === 0}>
				{option.value}
			</option>
		{/each}
	</select>
</div>
